#############################################################################
# Makefile for building: Final
# Generated by qmake (2.01a) (Qt 4.2.1) on: Thu Apr 14 17:06:40 2011
# Project:  Final.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -unix -o Makefile Final.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/lib64/qt4/include/QtCore -I/usr/lib64/qt4/include/QtCore -I/usr/lib64/qt4/include/QtGui -I/usr/lib64/qt4/include/QtGui -I/usr/lib64/qt4/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4/lib64 -lQtGui -L/usr/lib64/mysql -L/usr/lib64 -lpng -lSM -lICE -lXi -lXrender -lXrandr -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bacondemo.C \
		baconwindow.C \
		Key.cpp \
		Keyboard.cpp \
		main.C \
		tetrixboard.C \
		tetrixpiece.C moc_bacondemo.cpp \
		moc_baconwindow.cpp \
		moc_Key.cpp \
		moc_Keyboard.cpp \
		moc_tetrixboard.cpp
OBJECTS       = bacondemo.o \
		baconwindow.o \
		Key.o \
		Keyboard.o \
		main.o \
		tetrixboard.o \
		tetrixpiece.o \
		moc_bacondemo.o \
		moc_baconwindow.o \
		moc_Key.o \
		moc_Keyboard.o \
		moc_tetrixboard.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		Final.pro
QMAKE_TARGET  = Final
DESTDIR       = 
TARGET        = Final

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Final.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/lib64/libQtGui.prl \
		/usr/lib64/qt4/lib64/libQtCore.prl
	$(QMAKE) -unix -o Makefile Final.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/g++.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/lib64/libQtGui.prl:
/usr/lib64/qt4/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Final.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Final1.0.0 || $(MKDIR) .tmp/Final1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Final1.0.0/ && $(COPY_FILE) --parents bacondemo.h baconwindow.h Key.h Keyboard.h tetrixboard.h tetrixpiece.h .tmp/Final1.0.0/ && $(COPY_FILE) --parents bacondemo.C baconwindow.C Key.cpp Keyboard.cpp main.C tetrixboard.C tetrixpiece.C .tmp/Final1.0.0/ && (cd `dirname .tmp/Final1.0.0` && $(TAR) Final1.0.0.tar Final1.0.0 && $(COMPRESS) Final1.0.0.tar) && $(MOVE) `dirname .tmp/Final1.0.0`/Final1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Final1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/lib64/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_bacondemo.cpp moc_baconwindow.cpp moc_Key.cpp moc_Keyboard.cpp moc_tetrixboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_bacondemo.cpp moc_baconwindow.cpp moc_Key.cpp moc_Keyboard.cpp moc_tetrixboard.cpp
moc_bacondemo.cpp: tetrixpiece.h \
		baconwindow.h \
		bacondemo.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) bacondemo.h -o moc_bacondemo.cpp

moc_baconwindow.cpp: baconwindow.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) baconwindow.h -o moc_baconwindow.cpp

moc_Key.cpp: Key.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) Key.h -o moc_Key.cpp

moc_Keyboard.cpp: Key.h \
		Keyboard.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) Keyboard.h -o moc_Keyboard.cpp

moc_tetrixboard.cpp: tetrixpiece.h \
		baconwindow.h \
		tetrixboard.h \
		/usr/lib64/qt4/bin/moc
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) tetrixboard.h -o moc_tetrixboard.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

bacondemo.o: bacondemo.C bacondemo.h \
		tetrixpiece.h \
		baconwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bacondemo.o bacondemo.C

baconwindow.o: baconwindow.C bacondemo.h \
		tetrixpiece.h \
		baconwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baconwindow.o baconwindow.C

Key.o: Key.cpp Key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Key.o Key.cpp

Keyboard.o: Keyboard.cpp Keyboard.h \
		Key.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Keyboard.o Keyboard.cpp

main.o: main.C baconwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

tetrixboard.o: tetrixboard.C tetrixboard.h \
		tetrixpiece.h \
		baconwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tetrixboard.o tetrixboard.C

tetrixpiece.o: tetrixpiece.C tetrixpiece.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tetrixpiece.o tetrixpiece.C

moc_bacondemo.o: moc_bacondemo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bacondemo.o moc_bacondemo.cpp

moc_baconwindow.o: moc_baconwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baconwindow.o moc_baconwindow.cpp

moc_Key.o: moc_Key.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Key.o moc_Key.cpp

moc_Keyboard.o: moc_Keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Keyboard.o moc_Keyboard.cpp

moc_tetrixboard.o: moc_tetrixboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tetrixboard.o moc_tetrixboard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

